#!/bin/bash
source /home/chrome/.bashrc
export PULSE_RUNTIME_PATH="/run/user/$(id -u)/pulse/"
export XDG_RUNTIME_DIR="/run/user/$(id -u)"
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
export DISPLAY=:0.0
export LD_LIBRARY_PATH=/usr/lib/
/usr/bin/ffmpeg -video_size 1024x768 -framerate 25 -f x11grab -i :0.0 -f pulse -ac 2 -i default /home/chrome/dist/record/$(date +%b%d-%H-%M-%S).mkv

