#!/bin/bash
source /home/zuplex/.bashrc
export PULSE_RUNTIME_PATH="/run/user/$(id -u)/pulse/"
export XDG_RUNTIME_DIR="/run/user/$(id -u)"
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
export DISPLAY=:0.0
export LD_LIBRARY_PATH=/usr/lib/:/opt/zoom/

/home/zuplex/.usr/system/pea/scripts/startmeeting &
